### PR TITLE
Reduce package size

### PR DESCRIPTION
**Pull request by yakushabb**
- To be tested carefully.

### CODE REVIEW

**Comment by ghost** [comment]
This patch reduces the package size from 183MB to 144MB but needs to be tested carefully. 

image

**Comment by ghost** [comment]
Do you need all these binaries?

```
128K	./bin/y4mscaler
32K	./bin/ppmtoy4m
96K	./bin/a52dec
0	./bin/xxh32sum
40K	./bin/dcadec
24K	./bin/lav2yuv
16K	./bin/corrupt_mpeg2
24M	./bin/ffprobe
16K	./bin/gen-enc-table
20K	./bin/y4mblack
40K	./bin/yuvdenoise
20K	./bin/yuyvtoy4m
52K	./bin/yuvcorrect_tune
20K	./bin/ypipe
72K	./bin/xxhsum
32K	./bin/pnmtoy4m
4,0K	./bin/lav2avi.sh
4,0K	./bin/dtsdec
28K	./bin/lavaddwav
28K	./bin/jpeg2yuv
52K	./bin/soundstretch
20K	./bin/extract_mpeg2
20K	./bin/lav2mpeg
28K	./bin/yuvmedianfilter
136K	./bin/y4mdenoise
32K	./bin/yuvdeinterlace
0	./bin/xxh128sum
188K	./bin/daikhan
24K	./bin/pgmtoy4m
20K	./bin/yuvinactive
24K	./bin/y4munsharp
20K	./bin/extract_dca
56K	./bin/faad
16K	./bin/yuv-distortion
16K	./bin/y4mhist
132K	./bin/mp2enc
16K	./bin/lav2wav
24M	./bin/ffplay
28K	./bin/bjoentegaard
80K	./bin/rd-curves
24K	./bin/y4mspatialfilter
28K	./bin/y4mcolorbars
20K	./bin/extract_a52
60K	./bin/acceleration_speed
40K	./bin/yuvkineco
24K	./bin/yuv2lav
36K	./bin/fluidsynth
16K	./bin/transist.flt
28K	./bin/y4mtoppm
48K	./bin/mpeg2enc
16K	./bin/tests
36K	./bin/y4mstabilizer
28K	./bin/lavtc.sh
16K	./bin/block-rate-estim
20K	./bin/lavtrans
28K	./bin/y4mtopnm
44K	./bin/yuvcorrect
16K	./bin/lavinfo
60K	./bin/yuvscaler
16K	./bin/multiblend.flt
16K	./bin/y4mivtc
52K	./bin/mpeg2dec
16K	./bin/mjpeg_simd_helper
28K	./bin/anytovcd.sh
28K	./bin/lavpipe
24M	./bin/ffmpeg
4,0K	./bin/mpegtranscode
24K	./bin/yuvfps
0	./bin/xxh64sum
28K	./bin/yuvycsnoise
16K	./bin/y4mtoyuv
20K	./bin/y4minterlace
32K	./bin/png2yuv
20K	./bin/yuv4mpeg
24K	./bin/y4mshift
16K	./bin/matteblend.flt
32K	./bin/mplex
73M	./bin
```

**Comment by ghost** [comment]
From 188MB to 47.3MB!

image

**Comment by ghost** [comment]
Inspired from several sources including Clapper

- https://github.com/flathub/com.github.rafostar.Clapper/blob/master/com.github.rafostar.Clapper.json

**Comment by ghost** [comment]
@realmazharhussain Could you look these hacks.

**Comment by realmazharhussain** [comment]
bot, build

**Comment by realmazharhussain** [comment]
> Do you need all these binaries?
> 
> ```
> 128K	./bin/y4mscaler
> 32K	./bin/ppmtoy4m
> 96K	./bin/a52dec
> 0	./bin/xxh32sum
> 40K	./bin/dcadec
> 24K	./bin/lav2yuv
> 16K	./bin/corrupt_mpeg2
> 24M	./bin/ffprobe
> 16K	./bin/gen-enc-table
> 20K	./bin/y4mblack
> 40K	./bin/yuvdenoise
> 20K	./bin/yuyvtoy4m
> 52K	./bin/yuvcorrect_tune
> 20K	./bin/ypipe
> 72K	./bin/xxhsum
> 32K	./bin/pnmtoy4m
> 4,0K	./bin/lav2avi.sh
> 4,0K	./bin/dtsdec
> 28K	./bin/lavaddwav
> 28K	./bin/jpeg2yuv
> 52K	./bin/soundstretch
> 20K	./bin/extract_mpeg2
> 20K	./bin/lav2mpeg
> 28K	./bin/yuvmedianfilter
> 136K	./bin/y4mdenoise
> 32K	./bin/yuvdeinterlace
> 0	./bin/xxh128sum
> 188K	./bin/daikhan
> 24K	./bin/pgmtoy4m
> 20K	./bin/yuvinactive
> 24K	./bin/y4munsharp
> 20K	./bin/extract_dca
> 56K	./bin/faad
> 16K	./bin/yuv-distortion
> 16K	./bin/y4mhist
> 132K	./bin/mp2enc
> 16K	./bin/lav2wav
> 24M	./bin/ffplay
> 28K	./bin/bjoentegaard
> 80K	./bin/rd-curves
> 24K	./bin/y4mspatialfilter
> 28K	./bin/y4mcolorbars
> 20K	./bin/extract_a52
> 60K	./bin/acceleration_speed
> 40K	./bin/yuvkineco
> 24K	./bin/yuv2lav
> 36K	./bin/fluidsynth
> 16K	./bin/transist.flt
> 28K	./bin/y4mtoppm
> 48K	./bin/mpeg2enc
> 16K	./bin/tests
> 36K	./bin/y4mstabilizer
> 28K	./bin/lavtc.sh
> 16K	./bin/block-rate-estim
> 20K	./bin/lavtrans
> 28K	./bin/y4mtopnm
> 44K	./bin/yuvcorrect
> 16K	./bin/lavinfo
> 60K	./bin/yuvscaler
> 16K	./bin/multiblend.flt
> 16K	./bin/y4mivtc
> 52K	./bin/mpeg2dec
> 16K	./bin/mjpeg_simd_helper
> 28K	./bin/anytovcd.sh
> 28K	./bin/lavpipe
> 24M	./bin/ffmpeg
> 4,0K	./bin/mpegtranscode
> 24K	./bin/yuvfps
> 0	./bin/xxh64sum
> 28K	./bin/yuvycsnoise
> 16K	./bin/y4mtoyuv
> 20K	./bin/y4minterlace
> 32K	./bin/png2yuv
> 20K	./bin/yuv4mpeg
> 24K	./bin/y4mshift
> 16K	./bin/matteblend.flt
> 32K	./bin/mplex
> 73M	./bin
> ```

Out of all these, we only need `./bin/daikhan`. Others can be removed.

**Comment by realmazharhussain** [comment]
> Out of all these, we only need ./bin/daikhan. Others can be removed.

On second thought, we don't need to remove any more binaries. After your changes, the total size of `/app/bin/` is 2.7 MB.

The major contributors of the huge size were

```
24M	./bin/ffprobe
24M	./bin/ffplay
24M	./bin/ffmpeg
```

which are automatically removed by using `ffmpeg-full` extension instead of including a manually compiled version of FFmpeg.

**Comment by realmazharhussain** [comment]
I have tested the different file types I have. They all work as before. I am marking this pull request as "approved". I will merge this tomorrow. In the meantime, If there are any changes to be pushed, or testing to be done, let me know and I'll delay the merge.

**Review by realmazharhussain — APPROVED** [review]

**Comment by ghost** [comment]
I've reorded the cleanup entries. I will test again some common formats with the latest build.

**Comment by ghost** [comment]
Is this warning important?

> (daikhan:2): GStreamer-WARNING **: 20:18:26.503: External plugin loader failed. This most likely means that the plugin loader helper binary was not found or could not be run. You might need to set the GST_PLUGIN_SCANNER environment variable if your setup is unusual. This should normally not be required though.

**Comment by realmazharhussain** [comment]
> Is this warning important?
> 
> > (daikhan:2): GStreamer-WARNING **: 20:18:26.503: External plugin loader failed. This most likely means that the plugin loader helper binary was not found or could not be run. You might need to set the GST_PLUGIN_SCANNER environment variable if your setup is unusual. This should normally not be required though.

Yes. It, at least, needs to be investigated.

**Comment by realmazharhussain** [comment]
I tried to investigate it, but after launching the app a few times, the warning is gone now. The last way I tried to launch Daikhan was running `flatpak run --branch=test --command=sh io.gitlab.daikhan.stable`, and then `daikhan` command inside the newly spawned shell. After that, I can't reproduce the warning.

Since plugins seem to be loading just fine, even with the warning, I think we can ignore it for now.

I will merge the PR tomorrow, unless any new issues arise.

**Review by realmazharhussain — APPROVED** [review]

**Comment by realmazharhussain** [comment]
I forgot to merge yesterday. So, doing it today.

**Pull request merged**
